//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Asp_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public decimal ID_de_inventario { get; set; }
        public string Pieza { get; set; }
        public string Codigo { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Precio { get; set; }
        public string Cantidad { get; set; }
        public string Numero_de_estante { get; set; }
        public string Fabricante { get; set; }
        public string Descripcion { get; set; }
        public string Fecha_de_registro { get; set; }
    }
}
